### ISSUE TITLE
%n can fail if the .nobackup itself is a link

### ISSUE THREAD

**Issue by dpc** [miekg/rdup#20]
```
(gdb) run /dev/null ~/ -F '%b %n\n' > x.out
Starting program: /home/dpc/opt/src/rdup/rdup /dev/null ~/ -F '%b %n\n' > x.out
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.22-7.fc23.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7020b3a in strlen () from /lib64/libc.so.6
=> 0x00007ffff7020b3a <strlen+42>:      f3 44 0f 6f 20  movdqu (%rax),%xmm12
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.6-19.fc23.x86_64 glib2-2.46.2-1.fc23.x86_64 libacl-2.2.52-10.
fc23.x86_64 libarchive-3.1.2-14.fc23.x86_64 libattr-2.4.47-14.fc23.x86_64 libxml2-2.9.3-2.fc23.x86_64 lzo-2.08-5.fc23.x86_64 nettle-
3.1.1-6.fc23.x86_64 openssl-libs-1.0.2e-3.fc23.x86_64 pcre-8.38-4.fc23.x86_64 xz-libs-5.2.1-3.fc23.x86_64 zlib-1.2.8-9.fc23.x86_64
(gdb) bt
#0  0x00007ffff7020b3a in strlen () from /lib64/libc.so.6
#1  0x00007ffff70046ef in fputs () from /lib64/libc.so.6
#2  0x0000000000403e83 in entry_print_data (e=0x612360, n=<optimized out>, out=0x7ffff7352640 <_IO_2_1_stdout_>) at gfunc.c:307
#3  entry_print (out=0x7ffff7352640 <_IO_2_1_stdout_>, pm=<optimized out>, pm@entry=0x1, e=e@entry=0x612360, fmt=<optimized out>)
    at gfunc.c:390
#4  0x000000000040414b in gfunc_new (data=0x612360, value=0x1, usr=<optimized out>) at gfunc.c:528
#5  0x00007ffff7b19aa6 in g_tree_foreach () from /lib64/libglib-2.0.so.0
#6  0x0000000000402b68 in main (argc=0x2, argv=0x7fffffffd970) at rdup.c:476
(gdb) frame 3
#3  entry_print (out=0x7ffff7352640 <_IO_2_1_stdout_>, pm=<optimized out>, pm@entry=0x1, e=e@entry=0x612360, fmt=<optimized out>)
    at gfunc.c:390
390                                     entry_print_data(out, *pos, e);
(gdb) p *e
$1 = {
  plusmin = 0x0, 
  f_lnk = 0x0, 
  f_name = 0x612330 "/home/dpc/.linuxbrew/.nobackup", 
  f_target = 0x0, 
  f_name_size = 0x1e, 
  f_uid = 0x3e8, 
  f_user = 0x6112b0 "dpc", 
  f_gid = 0x3e8, 
  f_group = 0x6112d0 "dpc", 
  f_mode = 0xa1ff, 
  f_ctime = 0x56b24f40, 
  f_mtime = 0x56b24f40, 
  f_atime = 0x56b24f5e, 
  f_size = 0x25, 
  f_dev = 0x2d, 
  f_rdev = 0x0, 
  f_ino = 0xb81e09
}
```

**Comment by dpc** [comment]
> ls -alh ~/.linuxbrew/.nobackup 
lrwxrwxrwx. 1 dpc dpc 37 Feb  3 11:04 /home/dpc/.linuxbrew/.nobackup -> ../dot/linuxbrew/.linuxbrew/.nobackup

**Comment by dpc** [comment]
I've found a root of a problem. Will submit a fix later.
